### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by djdanby** [pchoiniere/FSModManager#4]
I found a new error. I can not save my settings. Evertime i get this error. U know what that is? I dont know what im doing wrong now.

![ErrorModManager](https://github.com/pchoiniere/FSModManager/assets/38318655/eeddd0c4-da70-4160-933c-783de2b64d5c)

**Comment by pchoiniere** [comment]
One of the mods on the server has characters the mod manager is having problem understanding.  I bet this happened after you added a new mod. If you figure what mod is doing this, you can send it to me and I can see if there is a fix for it.

**Comment by pchoiniere** [comment]
Another way you can help me figure out what might be the problem is open the browser to the dedicated server URL, right click in the empty area to the right of the mods and select "View page source", then right click again and click "Save as..." to save it to a file and send that file to me. The mod manager is having issues parsing this file.

**Comment by djdanby** [comment]
Ok. I'll have a look later when I get back from work. ;)

**Comment by djdanby** [comment]
Here the html File. I can not upload as a html file. Thats why it is json.

[neu 7.json](https://github.com/pchoiniere/FSModManager/files/15015132/neu.7.json)

**Comment by pchoiniere** [comment]
I figured out that the instructions I gave you will not pull down the mod page html the way it does in the FSModManager, so I added a debug menu option. Hold down shift while right clicking the mod folder button and click "Download mod page html (debugging)".
